# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Grey Design
email: info@himatt.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Matt Grey&mdash;visual, UX and type designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://himatt.com" # the base hostname & protocol for your site
timezone: Europe/London
twitter_username: mattgreydesign
github_username:  mattgreydesign

# Build settings
markdown: kramdown

# Sass output
sass:
  style: compressed

# Configure site collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  fonts:
    output: true
    permalink: /fonts/:path/

# Set default post types

# defaults:
#   -
#     scope:
#       path: "projects"
#       type: "pages"
#     values:
#       layout: "project"
#       author: "Matt"
#       category: "project"
#   -
#     scope:
#       path: "fonts"
#       type: "pages"
#     values:
#       layout: "font"
#       author: "Matt"
#       category: "font"
